version: '3'

services:
  recommender-service:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
